### ISSUE TITLE
No blanks in letter bag

### ISSUE THREAD

**Issue by SimonW68** [sta314/scrabble_ai#1]
Are blank tiles not handled ?

**Comment by sta314** [comment]
Blank tiles are not considered. Adding it would introduce branches to computations, which will increase computational time.

First, you can add blank tiles to the pouch (with a symbol).

Modifying following to allow branches to modify game logic to accept such tiles in words:
https://github.com/sta314/scrabble_ai/blob/dbc0ac8a6564bd773db9c8f2a94500bfc3e31b81/AI/trie.py#L17-L23

Modifying following to allow branches for ai computations to find such combinations:
https://github.com/sta314/scrabble_ai/blob/dbc0ac8a6564bd773db9c8f2a94500bfc3e31b81/AI/scrabble_wordfinder.py#L27-L66

It should be possible with these changes.
